name:                PolygonArt
version:             0.1.0.0
github:              "ahaubner/PolygonArt"
license:             GPL-3
author:              "ahaubner"
#maintainer:          "example@example.com"
copyright:           "2018 ahbnr"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Random art generator
# category:            Random art

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ahaubner/PolygonArt#readme>

dependencies:
- base >= 4.7 && < 5
- array == 0.5.2.0
- random == 1.1

library:
  source-dirs: src

executables:
  polygon:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PolygonArt

tests:
  PolygonArt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PolygonArt
    - tasty == 1.0.1.1
    - tasty-smallcheck
    - tasty-hunit
    - composition == 1.0.2.1
